apiVersion: batch/v1
kind: CronJob
metadata:
  name: nightly-game-server-backups
spec:
  schedule: "0 18 * * *" # Runs every night at 6PM UTC -> 6AM NZST
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: restic-backup
            image: restic/restic:latest
            env:
            - name: RESTIC_REPOSITORY
              valueFrom:
                secretKeyRef:
                  name: restic-secret
                  key: repository
            - name: RESTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: restic-secret
                  key: password
            command:
              - "/bin/sh"
              - "-c"
              - |
                echo "Starting Fabric Minecraft backup..."
                restic backup /data/fabric-minecraft --tag fabric-minecraft -o sftp.args="-vv -i /root/.ssh/id_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o PubkeyAcceptedAlgorithms=+ssh-rsa"
                
                echo "Starting Terraria backup..."
                restic backup /data/terraria --tag terraria -o sftp.args="-vv -i /root/.ssh/id_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o PubkeyAcceptedAlgorithms=+ssh-rsa"
                
                echo "Backups completed."
            volumeMounts:
            - mountPath: /data/fabric-minecraft
              name: fabric-minecraft-vol
              readOnly: true
            - mountPath: /data/terraria
              name: terraria-vol
              readOnly: true
            - mountPath: /root/.ssh/id_rsa
              subPath: id_rsa
              name: restic-ssh-keys-vol
              readOnly: true
          restartPolicy: OnFailure
          volumes:
          - name: fabric-minecraft-vol
            persistentVolumeClaim:
              claimName: fabric-vanilla-minecraft-backups-pvc
          - name: terraria-vol
            persistentVolumeClaim:
              claimName: terraria-pvc
          - name: restic-ssh-keys-vol
            secret:
              secretName: restic-secret
              defaultMode: 0400
              items:
              - key: ssh-key-private
                path: id_rsa