apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: allthemods-10-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: allthemods-10-backups-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: allthemods-10-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: allthemods-10
  template:
    metadata:
      labels:
        app: allthemods-10
    spec:
      containers:
        - name: allthemods-10
          image: itzg/minecraft-server
          ports:
            - containerPort: 25565
          env:
            - name: EULA
              value: "TRUE"
            - name: ICON
              value: "https://static.wikia.nocookie.net/deltarune/images/b/ba/Man_overworld_tree.gif"
            # Modded Server Settings
            - name: MODPACK_PLATFORM
              value: "AUTO_CURSEFORGE"
            - name: CF_PAGE_URL
              value: "https://www.curseforge.com/minecraft/modpacks/all-the-mods-10"
            # JVM Options
            # https://docker-minecraft-server.readthedocs.io/en/latest/configuration/jvm-options
            - name: MEMORY # Should be 80% of container mem
              value: 8G
            - name: USE_MEOWICE_FLAGS
              value: "true"
            # Server Properties
            # https://docker-minecraft-server.readthedocs.io/en/latest/configuration/server-properties/
            - name: DIFFICULTY
              value: "normal"
            - name: OPS
              value: |-
                Wingmann
            - name: WHITELIST
              value: |-
                Wingmann
            - name: SPAWN_PROTECTION
              value: "0"
            - name: MOTD
              value: "§e☀ Rebellion §aMinecraft§r - §bAll The Mods 10§r\n§7 * Well, there is a server here."
          resources:
            requests:
              memory: "10Gi"
              cpu: "1000m"
            limits:
              memory: "10Gi"
          volumeMounts:
            - mountPath: /data
              name: allthemods-10-data
        - name: allthemods-10-backups
          image: itzg/mc-backup
          #imagePullPolicy: Never
          securityContext:
            runAsUser: 1000
          env:
            - name: BACKUP_INTERVAL
              value: "24h"
          volumeMounts:
            - mountPath: /data
              name: allthemods-10-data
              readOnly: true
            - mountPath: /backups
              name: allthemods-10-backups
      volumes:
        - name: allthemods-10-data
          persistentVolumeClaim:
            claimName: allthemods-10-pvc
        - name: allthemods-10-backups
          persistentVolumeClaim:
            claimName: allthemods-10-backups-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: allthemods-10-service
spec:
  type: NodePort
  selector:
    app: allthemods-10
  ports:
    - protocol: TCP
      port: 25565
      targetPort: 25565
      nodePort: 30002
