apiVersion: v1
kind: Namespace
metadata:
  name: honeypot-mc
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: honeypot-postgres
  namespace: honeypot-mc
spec:
  instances: 1
  storage:
    size: 1Gi