---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-tunnel-secret
  namespace: cloudflared
spec:
  encryptedData:
    token: AgCvnOx+IJgd+u5Xc0lqE48iC2DwDPzIvKCfrUTiPrDzWMo+rlns2Xl0MtWjVBmxTYYaFd09qjNcG66z9I7kTZEQvWmbzrbEejwf1BOztc1ZXxesm7sWk0gc2E1OR5kJQRybfLDelpjRROl2DYusSYEhoXbGpvMrMNDPo+uil6te/c0UZmY2hDwndx0zyHceN9rMrAkWIHz1gikWapNs2/IRMpgrakQZ9rAqA38Tm4HdzLzBCPqfhYeNnCKrHQc8xM2yTzoS9cZS70iLXxgbfereLmCVDyeV7uQ/2Qg4vzqXL9YEHa+OAT7jeNWUVtsd5Q29TkVm6b9a84Du4tQZD/u/zUXPhjpMe91g0XdYJ80+gQqQx30Xs+O0O4pzNcxxhjsJLgESXAyAAFJFDEVBkk/V+irQR6gMdvHvcqdznPMRlvqcSmEWHJ0erO+aJ2kl6SyxEFLEGspOo9rjofirOruSM1wzFX7FyFvQ3r3cZImPh4CV4jKhot6lCX9rIwFITf9tG5S9QYvOnHu4AR6OIJjHZSaFKTyBhM6UA1oTmtZYT8DdNgShFQMUo2hUZCn3GYb7xvRSwBsUrnwaVVv7Ro1U5cPQbDE9/emq3PSVvs+P0uKJm37JpvomLlvDEPW75LSGZ3QJ7vEHQOI59myJU7p/Xvt/OIAdEaV3c2qvTpRX6WmU5T03sVHg7Ge3LzU8HIKanrE3ZsrCr3E3uap9KgfSspKmnlu8O/0Jo9bkrbgU5kdl9ajpEw3J4HfBUiogTH6ucmsdJz7odL5dAkKWfNHn5ULAGQciwMuwUkJegdVnwcPuwvdP7dcamZIlPmGb7TJkuR4VgeP+2P7Qx8O/oa19H8reaYcIuEasmI4GmQvHghS6OTmtWeW+MVaDjbacZeQR8e+V2v+lLB+Fp7zqM6fdW4c8LshpoD4ngYmLVjo2lZTvp1VJRfaw
  template:
    metadata:
      name: cloudflared-tunnel-secret
      namespace: cloudflared
