---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-tunnel-secret
  namespace: cloudflared
spec:
  encryptedData:
    token: AgCKw29f3O3tbxJG2NcvkvA4jpRMh+PoWnKKeFoqx4DzyfKy8MzkoxOmyU90ltKb714k3wNJtQPWpfb73bceVaBJqHDfpj7CbULKEHcMfr1AdA2w+eNmWvltZacNp/ZASvBMsYyyM5ykkio4Zf7432vajQzXipfx58VCAR3HnC/VaCDakxBDF5ndbFzPhUHmMWdyl2IcUpO3gO6I5fDm9eDegVElz725ckBDul8YIK1af16FKC4xSYtTvEchWePM20/ldic3e5KrrkOZDbKbh9UEGhc3GI7kEXQJuk22N+s5xN1scP3oniWYSrWh0W14+iuJJnzheA7H/pmV7N+3norStqOlaEnMlXWYW3g/91g9CQAW0L60+YUzMBUtqHzVjRPAZwhNRn/GdtG2nl+QJzXARu3NZ7Rj1Anh3fnBaIBKHCfMY5XRzBourUWlNeCHBmKU5niCQvGHBpBPxJD113GnAI28+V+5fYgGwdPbJooCkZYJlBv1k5TVivBq5QZnZtNFV46B23f/VzO3t5G7ppe1MPbiFBKJUNyOYPWF8qho69qid87bAYAv0db231gJHW/rgHM6r+QdIDWq4EmhMeDTBFsvprw1UcDKqz0fJlxGmfp1cd7jJpZicCsG71XueWwfqEbJh7wcrzNfQs4/TFfjadGJpwL+z/QpbxEGB7cBbpMJlc4QIvBgXDAagAxaTvYS5blhiRW3DBH3IadW9UeF7LYnKNKH36nx/unQQsUf/Nrx2ItyhblGxW4qGLompSh2b4bc6WP74oUifwhrDv0+nW1HHMQ+ovr2ymknYIel5wZWW54rky7rFjTwM2ZZPJ84F+Pe4zXRJQH1BKAjIR1l1Znz2MpgSUE/vM6qgT6mgL5i0WrEI9gUtMctWEfgVnGumCbLN+9Az1JLKKBv7H8lrZ/H2h7qpXPFdK3f09cV0olWSByyCocM
  template:
    metadata:
      name: cloudflared-tunnel-secret
      namespace: cloudflared
