---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared
  namespace: cloudflared
spec:
  encryptedData:
    token: AgAaF84gBTNoQe1+5jXnULcP8nr9wbVpmURU7QXCTDRcTUTK4wkJnHmszkmJ3U57+0ISV3rapQNWbWcDevfK3wT3cOZukldf19kkoGy4nIqU5OIThx9C+WL0/AJ2dfE4q789KGjsexxRzbLwgE1sgU2Wjh1s60lcwLp6vVulweypmZ7uPPSRZTI+q0aolL3RbiiikpKPrA7Ap0xhqRuFoZ9BpsMaJLJkhJ1CJtETsh6Ptwjzdqt8A8myJ7FIPvBNuSTctU97q3h9sjhLIxqZ8tv0biTgJJ2RtOTKk516dbo8YzW3HgC/KXiQhphKFfWvDVr8zKBcyp+Yb7fiCwyB7bqjTlsorBlhexZwK1RyawZfhleR62HPFFRO6yNJGrdNUlVsIFp4GPRRit0EeGGdxGFVyYYU2lPeT18JISOJkmflyk/xt9ts+REt1sjMK1uqkhfarC/8XkhvVAgQb6WHY1AGZGJU8RCYrd8FIfrwHLRNaML4GAWvPaauwTRjMB/FLzM/Vktw24rOfjEZf/6g+/b7XIC40oEaSuV9BnzTa21z/CaJNwhuaud+lCgBKIR2po9xip0+0cEf6FXy2V1aq25hIOeBCVfGydOUFnV9inw0L6G3RIPP3VVuMyyKJE/MMVSG4NE3IPqaw6GuFJ2Nq4xE+iLzAbJi33o1OKgo+4jp4A1+8evvZ5h+L2zRwd9CD89OSW3Dd4vxLsDOGTEjp2PyjFKxa5iuNuYWcBnpUwaOvDVakLnVkUc86GFJ4FzmA5Kum3MrvkWU6ee1qUcHXo9jfyzNPJOZLDRDhd4li4afrkWCWLqDX5+sQQSwUzazuxUMkNW9svB0cTooK9B8HwItX16m/GY2xLc9OeAJq93SF+4rXZJhDLzZHkPVNypuzPANcdfkHOFYSJtlLejcSe2zBPX8hNxMO2PXim50mbS66aW0XFIh6qwp
  template:
    metadata:
      name: cloudflared
      namespace: cloudflared
