apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: terraria-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: terraria-server
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: terraria
  template:
    metadata:
      labels:
        app: terraria
    spec:
      containers:
        - name: terraria
          image: ryshe/terraria:vanilla-1.4.5.8
          ports:
            - containerPort: 7777
          args:
            - "-world"
            - "/root/.local/share/Terraria/Worlds/world.wld"
            - "-autocreate"
            - "2"
          resources:
            requests:
              memory: "2Gi"
              cpu: "1000m"
            limits:
              memory: "2Gi"
          volumeMounts:
            - mountPath: /root/.local/share/Terraria/Worlds
              name: terraria-world
      volumes:
        - name: terraria-world
          persistentVolumeClaim:
            claimName: terraria-pvc
          
---
apiVersion: v1
kind: Service
metadata:
  name: terraria-service
spec:
  type: NodePort
  selector:
    app: terraria
  ports:
    - protocol: TCP
      port: 7777
      targetPort: 7777
      nodePort: 30003
