apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fabric-vanilla-minecraft-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fabric-vanilla-minecraft-backups-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fabric-vanilla-minecraft-server
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: fabric-vanilla-minecraft
  template:
    metadata:
      labels:
        app: fabric-vanilla-minecraft
    spec:
      containers:
        - name: fabric-vanilla-minecraft
          image: itzg/minecraft-server
          ports:
            - containerPort: 25565
          env:
            # Server Type
            - name: TYPE
              value: "FABRIC"
            - name: VERSION
              value: "26.2"
            - name: MODRINTH_DOWNLOAD_DEPENDENCIES
              value: "required"
            - name: MODRINTH_PROJECTS
              value: |
                voxyserver:EsIPjK0A 
                dcintegration:ZZwadcBm
            # Server Properties
            - name: EULA
              value: "TRUE"
            - name: ICON
              value: "https://raw.githubusercontent.com/TomasBorsje/Cloud9/refs/heads/main/assets/fabric-vanilla-minecraft-server-icon.png"
            - name: OVERRIDE_ICON
              value: "true"
            # JVM Options
            # https://docker-minecraft-server.readthedocs.io/en/latest/configuration/jvm-options
            - name: MEMORY # Should be 80% of container mem
              value: 3G
            - name: USE_MEOWICE_FLAGS
              value: "true"
            # Server Properties
            # https://docker-minecraft-server.readthedocs.io/en/latest/configuration/server-properties/
            - name: DIFFICULTY
              value: "normal"
            - name: OPS
              value: |-
                Wingmann
            - name: WHITELIST
              value: |-
                Wingmann
            - name: ENFORCE_SECURE_PROFILE
              value: "false"
            - name: SPAWN_PROTECTION
              value: "0"
            - name: MOTD
              value: "§e☀ Rebellion §aMinecraft§r - §fVanilla§r\n§7 * Well, there is a server here."
          resources:
            requests:
              memory: "3.75Gi"
              cpu: "1000m"
            limits:
              memory: "3.75Gi"
          volumeMounts:
            - mountPath: /data
              name: fabric-vanilla-minecraft-data
        - name: fabric-vanilla-minecraft-backups
          image: itzg/mc-backup
          #imagePullPolicy: Never
          securityContext:
            runAsUser: 1000
          env:
            - name: BACKUP_INTERVAL
              value: "24h"
          volumeMounts:
            - mountPath: /data
              name: fabric-vanilla-minecraft-data
              readOnly: true
            - mountPath: /backups
              name: fabric-vanilla-minecraft-backups
      volumes:
        - name: fabric-vanilla-minecraft-data
          persistentVolumeClaim:
            claimName: fabric-vanilla-minecraft-pvc
        - name: fabric-vanilla-minecraft-backups
          persistentVolumeClaim:
            claimName: fabric-vanilla-minecraft-backups-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: fabric-vanilla-minecraft-service
spec:
  type: NodePort
  selector:
    app: fabric-vanilla-minecraft
  ports:
    - protocol: TCP
      port: 25565
      targetPort: 25565
      nodePort: 30004
