apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/cloudnative-pg/cloudnative-pg
    path: releases
    targetRevision: 4b5e244
    directory:
      include: cnpg-1.30.0.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: postgres
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
      enabled: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
